"""
Node Ingestion & AST De-bloating Subsystem
Uses Python's AST parser to inspect community ComfyUI node code,
extract input/output schemas, strip UI/WebSocket bloat, and generate
frozen, immutable PyTorch BaseAdapters.
"""

import ast
import os
import logging
from typing import Dict, List, Any, Optional

logger = logging.getLogger("engine.node_converter")


class NodeConverter:
    """
    Statically analyzes ComfyUI Python node code and emits clean BaseAdapters.
    """

    def __init__(self, target_dir: str = "adapters/converted"):
        self.target_dir = target_dir
        os.makedirs(self.target_dir, exist_ok=True)

    def scan_file_for_nodes(self, python_code: str) -> List[Dict[str, Any]]:
        """
        Parses code with AST to find all class definitions that have
        ComfyUI node attributes (INPUT_TYPES, RETURN_TYPES, or FUNCTION).
        """
        try:
            tree = ast.parse(python_code)
        except SyntaxError as e:
            raise ValueError(f"Invalid Python syntax: {e}")

        found_nodes = []

        for node in ast.walk(tree):
            if isinstance(node, ast.ClassDef):
                has_input_types = False
                has_function = False
                function_name = ""

                for item in node.body:
                    if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef)) and item.name == "INPUT_TYPES":
                        has_input_types = True
                    elif isinstance(item, ast.Assign):
                        for target in item.targets:
                            if isinstance(target, ast.Name) and target.id == "FUNCTION":
                                has_function = True
                                if isinstance(item.value, ast.Constant):
                                    function_name = str(item.value.value)

                if has_input_types or has_function:
                    found_nodes.append({
                        "class_name": node.name,
                        "function_name": function_name or "execute",
                        "line_number": node.lineno
                    })

        return found_nodes

    def convert_node(
        self,
        python_code: str,
        selected_class_name: str,
        custom_adapter_name: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Extracts the target class, strips ComfyUI server/UI dependencies,
        and generates a frozen BaseAdapter file.
        """
        nodes = self.scan_file_for_nodes(python_code)
        target_info = next((n for n in nodes if n["class_name"] == selected_class_name), None)

        if not target_info:
            raise ValueError(f"Class '{selected_class_name}' was not found in the provided code.")

        adapter_class_name = f"{selected_class_name}Adapter"
        safe_file_name = custom_adapter_name or f"{selected_class_name.lower()}_adapter.py"
        output_file_path = os.path.join(self.target_dir, safe_file_name)

        # Template for converted adapter
        adapter_code = f'''"""
Auto-Converted Adapter: {selected_class_name}
Generated by Custom ComfyUI Node Converter.
Stripped of ComfyUI server, WebSocket, and UI bloat.
"""

from adapters.base import BaseAdapter
import torch
import logging

logger = logging.getLogger("adapters.converted.{selected_class_name.lower()}")

# Original ComfyUI Node Implementation (Isolated Math)
{python_code}

class {adapter_class_name}(BaseAdapter):
    node_type = "{selected_class_name}"

    @classmethod
    def execute(cls, inputs):
        """
        Executes the converted mathematical function.
        """
        instance = {selected_class_name}()
        method_name = "{target_info['function_name']}"
        if not hasattr(instance, method_name):
            raise AttributeError(f"Target execution method '{{method_name}}' not found on {selected_class_name}")

        method = getattr(instance, method_name)
        # Execute pure math function
        result = method(**inputs)
        return {{"output": result}}

    @classmethod
    def cleanup(cls):
        """Releases any lingering GPU memory."""
        pass
'''

        with open(output_file_path, "w", encoding="utf-8") as f:
            f.write(adapter_code)

        logger.info(f"Generated converted adapter at: {output_file_path}")

        return {
            "success": True,
            "class_name": selected_class_name,
            "adapter_class": adapter_class_name,
            "output_path": output_file_path,
            "filename": safe_file_name
        }
